/* ticker-items.js — v4 */
(function(){ window.__TICKER_ITEMS = [
  { label:"Research\u2011Agent", category:"research", prompt:"Live\u2011Recherche starten (Plan \u2192 Triage \u2192 Synthese).", action:"research" },
  { label:"Cage\u2011Match", category:"research", prompt:"Zwei Modelle vergleichen (Prompt frei w\u00e4hlbar).", action:"cage-match" },
  { label:"GIST\u2192FACT\u2192CITE", category:"research", prompt:"Erst GIST (2 S\u00e4tze), dann FACT\u2011Bullets, dann CITE mit Quellen. Thema: [x].", action:null },
  { label:"Kontrast\u2011Paar", category:"research", prompt:"L\u00f6sung A konservativ vs. B radikal + 3 Kriterien, wann A/B \u00fcberlegen ist.", action:null },
  { label:"Socratic Debug", category:"research", prompt:"7 Gegenfragen zu [Ziel]; dann knappe Empfehlung.", action:null },
  { label:"Beweis\u2011CHECK", category:"research", prompt:"Markiere Aussagen ohne Evidenz; nenne exakt, was fehlt.", action:null },
  { label:"Rubrik\u2011Evaluator", category:"ops", prompt:"Scoring: Klarheit/K\u00fcrze/Konkretion/Korrektheit + 1 Fix je Rubrik.", action:null },
  { label:"Edge\u2011Case\u2011J\u00e4ger", category:"ops", prompt:"3 Edge\u2011Cases, die [Plan] sprengen + konkreter Fix je Fall.", action:null },
  { label:"Tabelle zuerst", category:"ops", prompt:"Antwort NUR als Tabelle: Schritt | Zeit | Tool | Output. Thema: [x].", action:null },
  { label:"One\u2011Minute\u2011Plan", category:"ops", prompt:"Ziel: [x]. 5 Schritte \u00e0 \u226412 W\u00f6rter \u2013 heute machbar.", action:null },
  { label:"Delta\u2011Edit", category:"writing", prompt:"Nur markierte Stellen verbessern; je \u00c4nderung Grund nennen.", action:null },
  { label:"Skelett\u2192F\u00fcllen", category:"writing", prompt:"Erst Inhalts\u2011Skelett (\u226410). Nach OK pr\u00e4zise ausformulieren.", action:null },
  { label:"Prompt\u2011Linter 2.0", category:"writing", prompt:"Diagnose: Ziel/Format/Constraints/Negativliste \u2192 bessere Version.", action:null },
  { label:"Kompressions\u2011Check", category:"writing", prompt:"Auf 30\u202f% komprimieren ohne Infoverlust (+ Ton\u2011Varianten).", action:null },
  { label:"Doppelte Perspektive", category:"writing", prompt:"Zwei Antworten: (1) Einsteiger (\u22644 S\u00e4tze), (2) Entscheider.", action:null },
  { label:"Pitch\u2011Formel 3\u00d73", category:"writing", prompt:"3 Pitches (rational/emotional/ungew\u00f6hnlich) + 1 Beleg.", action:null },
  { label:"Meeting\u2011Kurzprotokoll", category:"ops", prompt:"5 Bullets + 1 Entscheidung + 1 To\u2011do aus Transkript.", action:null },
  { label:"Redaktionsplan 10\u00d7", category:"ops", prompt:"4\u2011Wochen\u2011Plan (2 Posts/W) inkl. Hooks & Formate.", action:null },
  { label:"Evaluation\u2011Snippets", category:"ops", prompt:"5 Mini\u2011Tests (Input\u2192Soll\u2011Antwort) inkl. Score.", action:null },
  { label:"AI\u2011Act Quick\u2011Audit", category:"ops", prompt:"8\u2011Punkte\u2011Check kurz & pr\u00e4zise (Risiken, DPIA, Oversight\u2026).", action:null },
  { label:"Brand\u2011Voice Destillat", category:"writing", prompt:"5 Tonalit\u00e4ts\u2011Regeln + 1 Satz Stimm\u2011Statement.", action:null },
  { label:"Style\u2011Transfer kompakt", category:"creative", prompt:"Absatz X in extrahiertem Stil neu schreiben.", action:null },
  { label:"Transkript\u2192Kapitel", category:"creative", prompt:"Kapitel mit Timecodes + 1\u2011Satz\u2011Summary je Kapitel.", action:null },
  { label:"\ud83c\udf9e\ufe0f Storyboard\u2011Short", category:"visual", prompt:"6 Shots (Kamera + Licht) zu [Thema].", action:"storyboard" },
  { label:"Audio\u2011Hook 3\u00d7", category:"creative", prompt:"3 Hook\u2011Zeilen (\u226412 W\u00f6rter) + Takt/Feel.", action:null },
  { label:"Micro\u2011Copy 3\u00d7", category:"creative", prompt:"Bullets in 3 T\u00f6nen: neutral/frech/seri\u00f6s.", action:null },
  { label:"Mini\u2011RAG", category:"data", prompt:"Text in 5 Bl\u00f6cke (je 2 Zitate) + Q&A je Block.", action:null },
  { label:"Regel\u2011Extractor", category:"data", prompt:"7 WENN\u2026 DANN\u2026\u2011Regeln + 1 Beispiel je Regel.", action:null },
  { label:"Fact\u2011Guard", category:"data", prompt:"Vage Stellen (?) konkretisieren oder \u2018offen\u2019 markieren.", action:null },
  { label:"Daten\u2192Fragen", category:"data", prompt:"CSV lesen \u2192 7 pr\u00e4zise Fragen \u2192 3 beantworten.", action:null },
  { label:"Mail in 60\u202fSek.", category:"ops", prompt:"Betreff, 3 S\u00e4tze Kern, CTA (Ton: [freundlich/entschieden]).", action:null },
  { label:"\ud83d\uddbc\ufe0f Face\u2011Aging", category:"visual", prompt:"Eigenes Foto laden \u2192 +20 Jahre (realistisch).", action:"face-age" },
  { label:"\ud83d\uddbc\ufe0f Bild\u2011Varianten 4\u00d7", category:"visual", prompt:"Cinematic/analog/clean/vibrant aus deinem Bild.", action:"variations" },
  { label:"Agenten\u2011Startknopf", category:"research", prompt:"Schritt\u2011Plan (Suchs\u00e4tze, Kriterien, Gegenfragen) \u2013 nach jedem Schritt warten.", action:null },
  { label:"Modell\u2011Empfehlung", category:"research", prompt:"LLM\u2011Empfehlung f\u00fcr [Aufgabe] mit Budget [x], Datenschutz [y], Stil [z].", action:null },
  { label:"Heute testen (3\u00d7)", category:"ops", prompt:"3 Mini\u2011Experimente (\u226410\u202fMin.) inkl. Prompts & erwarteten Output.", action:null },
  { label:"Delta\u2011Vergleich", category:"ops", prompt:"2 Antworten nach 4 Rubriken (1\u20135) vergleichen + Nenner destillieren.", action:null },
  { label:"Kontrast\u2011Plan", category:"ops", prompt:"zwei Pl\u00e4ne (lean vs. deluxe) mit Aufwand/Kosten/Nutzen je Schritt.", action:null },
  { label:"News GIST\u2192FACT\u2192CITE", category:"research", prompt:"3 KI\u2011News: 2\u2011Satz\u2011Gist, 3 Fakten, 1 Zitat+Quelle.", action:null }
];})();
